<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>友達招待 - ドリームワールド</title>
<link href="{%$staticUrl%}/apps/island/css.css?v=1" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body onload="javascript:CrossFrame.setHeight(630);">
    <script type="text/javascript">
        var PAGE_NUM = {%$pageCount%};
        function hideAllPage()
        {
            var page = null;
            for(var i = 1; i <= PAGE_NUM; i++) {
                page = document.getElementById('page' + i);
                if (page) {
                    page.style.display = 'none';
                }
            }
        }
        
        function goPage(i)
        {
            var page = document.getElementById('page' + i);
            if (page) {
                hideAllPage();
                page.style.display = 'block';
            }
        }
    </script>
    
<div class="main">
    {%include file="menu.phtml"%}
	
   {%if $count == 0%}
    <div>您的所有平台好友已全都加入开心岛主!请邀请更多的站外好友!</div>
   {%else%}
    <div class="content">
      <form method="post" action="{%$baseUrl%}/invite/send" >
      <div class="yaoqing02-1"></div>
      
      <div class="yaoqing02-2">
      
      {% foreach from=$pageArray item=page key=key %}
        <div class="songli2-right" id="page{%$key+1%}" style="height:360px; width:700px;{% if $key>0 %}display:none;{%/if%}" >
            <ul>
                {%foreach from=$friendsArray[$key] item=friend%}
                <li style="float:left; padding:2px;">
	                <div class="mingzikuang">
	                    <div class="duoxuan">
	                      <p><input name="ids[]" type="checkbox" value="{%$friend.uid%}" /></p>
	                    </div>
	                    <div class="touxiang"><img src="{%$friend.thumbnail%}" /></div>
	                    <div class="mingzi">{%$friend.name|escape%}</div>
	                </div>
                </li>
                {%/foreach%}
            </ul>
        </div>
      
      {% /foreach %}
      </div>
    <div class="yaoqing02-3">
    
      {% if $pageCount > 1 %}
        <div align="right" style="width:650px">
            {% foreach from=$pageArray item=page key=key %}
               <a href="javascript:void(0);" onclick="goPage({%$key+1%});"> {%$key+1%} </a>&nbsp;
            {% /foreach %}  
        </div>
      {% /if %}
    </div>
    <div class="mashangyaoqing">
      <div align="center"><input type="image" src="{%$staticUrl%}/apps/island/images/gift/mashangyaoqing.gif" alt="友達招待" /></div>
    </div>
    </form>
    </div>
    {%/if%}

</div>

{%include file="footer.phtml"%}