<div class="title">
	<div class="menu">
		<div class="logo"><img src="{%$staticUrl%}/apps/island/images/sl_03_01.gif" alt="ドリームアイランド" /></div>
        <ul>       
        	<li><a href="{%$baseUrl%}/pay/webmoney"><img style="margin-top:-4px;" src="{%$staticUrl%}/apps/island/images/sl_15-2.gif" alt="チャージ" /></a></li>
        	<li><a href="{%$baseUrl%}/index/help"><img src="{%$staticUrl%}/apps/island/images/sl_13_1.gif" alt="ヘルプ" /></a></li>
        	<li><a href="http://mixi.jp/view_community.pl?id=5023218" target="_blank"><img src="{%$staticUrl%}/apps/island/images/bangpai.gif" alt="掲示板" /></a></li>
        	<li><a href="{%$baseUrl%}/gift/top"><img src="{%$staticUrl%}/apps/island/images/sl_09.gif" alt="ギフト" /></a></li>
        	<li><a href="{%$baseUrl%}/invite/top"><img src="{%$staticUrl%}/apps/island/images/sl_07.gif" alt="友達招待" /></a></li>
        	<li><a href="{%$baseUrl%}/index/flash"><img src="{%$staticUrl%}/apps/island/images/sl_05.gif" alt="ホーム" /></a></li>
        </ul>
	</div>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16276822-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? ' https://ssl' : ' http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- MIXI AD PROGRAM -->
<script type="text/javascript">/*<!--[
*/
(function(){
       var url =
"http://mixi.jp/ad_application_program_invoker.pl?appli_id=21618&ad_id=99ff07d54e99097bc6659ad88115d0cde30d9368";
       document.writeln(['<scri','pt src="',url,'&ts=',(new
Date).getTime(),'">','</scri','pt>'].join(''));
})();
--></script>
<!-- END -->