<div id="container">
<div class="pop_wrapper" style="height:500px;background-image:url('http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_background.jpg');border-radius:15px;">
<div style="height:55px;text-align: center;">
<font size="7">Stwórz swoją postać</font>
</div>
<div class="pop_top" style="cursor: move;">
<div class="pop_title" style="text-align:center;margin-top:15px;"></div>
<div class="pop_close"></div>
</div>
<div class="pop_dialog">
<div class="pop_container" align="center">
<table style="margin-left:40px">
<tbody>
<tr>
<td class="avatar" style="background: url(http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_empty_avatar.jpg) center center no-repeat;z-index : 4">
<img onclick="$('input:radio[name=visitCardThumbnail]:eq(0)').attr('checked',true)" style="cursor: pointer;" src="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_frame.png">
</td>
<td class="avatar" style="background: url(http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_male_01.jpg) center center no-repeat;z-index : 4">
<img onclick="$('input:radio[name=visitCardThumbnail]:eq(1)').attr('checked',true)" style="cursor: pointer;" src="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_frame.png">
</td>
<td class="avatar" style="background: url(http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_female_01.jpg) center center no-repeat;z-index : 4">
<img onclick="$('input:radio[name=visitCardThumbnail]:eq(2)').attr('checked',true)" style="cursor: pointer;" src="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_frame.png">
</td>
<td class="avatar" style="background: url(http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_male_02.jpg) center center no-repeat;z-index : 4">
<img onclick="$('input:radio[name=visitCardThumbnail]:eq(3)').attr('checked',true)" style="cursor: pointer;" src="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_frame.png">
</td>
<td class="avatar" style="background: url(http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_female_02.jpg) center center no-repeat;z-index : 4">
<img onclick="$('input:radio[name=visitCardThumbnail]:eq(4)').attr('checked',true)" style="cursor: pointer;" src="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_frame.png">
</td>
</tr>
<tr>
<td style="text-align:center;padding:10px;">
<span class="vcradio">
<input id="visitCard[0]" type="radio" checked="checked" value="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_empty_avatar.jpg" name="visitCardThumbnail">
</span>
</td>
<td style="text-align:center;padding:10px;">
<span class="vcradio">
<input id="visitCard[1]" type="radio" value="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_male_01.jpg" name="visitCardThumbnail">
</span>
</td>
<td style="text-align:center;padding:10px;">
<span class="vcradio">
<input id="visitCard[2]" type="radio" value="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_female_01.jpg" name="visitCardThumbnail">
</span>
</td>
<td style="text-align:center;padding:10px;">
<span class="vcradio">
<input id="visitCard[3]" type="radio" value="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_male_02.jpg" name="visitCardThumbnail">
</span>
</td>
<td style="text-align:center;padding:10px;">
<span class="vcradio">
<input id="visitCard[4]" type="radio" value="http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_female_02.jpg" name="visitCardThumbnail">
</span>
</td>
</tr>
</tbody>
</table>
<div style="text-align:center; padding:5px;">
<font size="5" style="vertical-align:middle;margin-right:10px">Płeć</font>
<span class="vcgenderradio">
<input type="radio" value="0" name="visitCardGender" valign="middle">
</span>
<label onclick="$('input:radio[name=visitCardGender]:eq(0)').attr('checked',true)">
<font size="5" style="vertical-align:middle;cursor: pointer">Kobieta</font>
</label>
<span class="vcgenderradio">
<input type="radio" checked="" value="1" name="visitCardGender" valign="middle">
</span>
<label onclick="$('input:radio[name=visitCardGender]:eq(1)').attr('checked',true)">
<font size="5" style="vertical-align:middle;cursor: pointer">Mężczyzna</font>
</label>
</div>
<div style="text-align:center;padding:5px;margin-left:200px;">
<table cellspacing="15">
<tbody>
<tr>
<td style="text-align: right;">
<font size="5" style="vertical-align:middle">Imię</font>
</td>
<td>
<input id="visitCardName" value="" style="border: 3px double #999; font-size: 16px;" valign="middle">
</td>
</tr>
<tr>
<td style="text-align: right;">
<font size="5" style="vertical-align:middle">Nazwisko</font>
</td>
<td>
<input id="visitCardLastName" value="" style="border: 3px double #999; font-size: 16px;" valign="middle">
</td>
</tr>
<tr>
<td style="text-align: right;">
<font size="5" style="vertical-align:middle">Urodziny</font>
</td>
<td>
<select id="visitCardBirthdayYear" style="border: 3px double #999; font-size: 16px;" size="1">
<option>1900</option>
<option>1901</option>
<option>1902</option>
<option>1903</option>
<option>1904</option>
<option>1905</option>
<option>1906</option>
<option>1907</option>
<option>1908</option>
<option>1909</option>
<option>1910</option>
<option>1911</option>
<option>1912</option>
<option>1913</option>
<option>1914</option>
<option>1915</option>
<option>1916</option>
<option>1917</option>
<option>1918</option>
<option>1919</option>
<option>1920</option>
<option>1921</option>
<option>1922</option>
<option>1923</option>
<option>1924</option>
<option>1925</option>
<option>1926</option>
<option>1927</option>
<option>1928</option>
<option>1929</option>
<option>1930</option>
<option>1931</option>
<option>1932</option>
<option>1933</option>
<option>1934</option>
<option>1935</option>
<option>1936</option>
<option>1937</option>
<option>1938</option>
<option>1939</option>
<option>1940</option>
<option>1941</option>
<option>1942</option>
<option>1943</option>
<option>1944</option>
<option>1945</option>
<option>1946</option>
<option>1947</option>
<option>1948</option>
<option>1949</option>
<option>1950</option>
<option>1951</option>
<option>1952</option>
<option>1953</option>
<option>1954</option>
<option>1955</option>
<option>1956</option>
<option>1957</option>
<option>1958</option>
<option>1959</option>
<option>1960</option>
<option>1961</option>
<option>1962</option>
<option>1963</option>
<option>1964</option>
<option>1965</option>
<option>1966</option>
<option>1967</option>
<option>1968</option>
<option>1969</option>
<option>1970</option>
<option>1971</option>
<option>1972</option>
<option>1973</option>
<option>1974</option>
<option>1975</option>
<option>1976</option>
<option>1977</option>
<option>1978</option>
<option>1979</option>
<option>1980</option>
<option>1981</option>
<option>1982</option>
<option>1983</option>
<option>1984</option>
<option>1985</option>
<option>1986</option>
<option>1987</option>
<option>1988</option>
<option>1989</option>
<option>1990</option>
<option>1991</option>
<option>1992</option>
<option>1993</option>
<option>1994</option>
<option>1995</option>
<option>1996</option>
<option>1997</option>
<option>1998</option>
<option>1999</option>
<option>2000</option>
<option>2001</option>
<option>2002</option>
<option>2003</option>
<option>2004</option>
<option>2005</option>
<option>2006</option>
<option>2007</option>
<option>2008</option>
<option>2009</option>
<option>2010</option>
</select>
<select id="visitCardBirthdayMonth" style="border: 3px double #999; font-size: 16px;" size="1">
<option>styczeń</option>
<option>luty</option>
<option>marzec</option>
<option>kwiecień</option>
<option>maj</option>
<option>czerwiec</option>
<option>lipiec</option>
<option>sierpień</option>
<option>wrzesień</option>
<option>październik</option>
<option>listopad</option>
<option>grudzień</option>
</select>
<select id="visitCardBirthdayDay" style="border: 3px double #999; font-size: 16px;" size="1">
<option>01</option>
<option>02</option>
<option>03</option>
<option>04</option>
<option>05</option>
<option>06</option>
<option>07</option>
<option>08</option>
<option>09</option>
<option>10</option>
<option>11</option>
<option>12</option>
<option>13</option>
<option>14</option>
<option>15</option>
<option>16</option>
<option>17</option>
<option>18</option>
<option>19</option>
<option>20</option>
<option>21</option>
<option>22</option>
<option>23</option>
<option>24</option>
<option>25</option>
<option>26</option>
<option>27</option>
<option>28</option>
<option>29</option>
<option>30</option>
<option>31</option>
</select>
</td>
</tr>
</tbody>
</table>
</div>
<div style="background-image:url('http://s3.amazonaws.com/imgs3.plinga.de/general/nk/vc_button.png');backgroung-repeat:no-repeat;cursor:pointer;height:36px;width:92px" onclick="goStartGame();"></div>
</div>
</div>
</div>
</div>