<?php

define('LANG_PLATFORM_FEED_MSG_00', 'Słońce, piasek i plaża przez cały rok! To wszystko znajdziesz w Wyspie Marzeń! Zagraj!');
define('LANG_PLATFORM_FEED_MSG_01', 'Moja wyspa została całkowicie zmieniona! Odwiedź mnie, a na pewno znajdzie się dla Ciebie mały prezent ;)');
define('LANG_PLATFORM_FEED_MSG_02', 'Moja wyspa została powiększona! Ty też możesz mieć własną w Wyspie Marzeń. Zagraj!');
define('LANG_PLATFORM_FEED_MSG_03', 'Mój budynek zwiększył liczbę Gwiazdek! Jest teraz jeszcze piękniejszy! Odwiedź mnie koniecznie, a pokaże Ci go!');
define('LANG_PLATFORM_FEED_MSG_04', 'Mała tratwa czy luksusowy statek? O którym z nich marzysz? Zagraj i kup jeden z nich!');
define('LANG_PLATFORM_FEED_MSG_05', 'Właśnie buduję kolejny port, co oznacza, że mogę przyjąć jeszcze więcej turystów! Interes się kręci :)');
define('LANG_PLATFORM_FEED_MSG_06', 'Nowy obiekt w Wyspie Marzeń! Wow! Jest niesamowity!');
define('LANG_PLATFORM_FEED_MSG_07', 'Je! Zdobywam kolejny tutuł: <title_name>! Zarządzanie własną wyspą to świetna zabawa! Zagraj i przekonaj się!');
define('LANG_PLATFORM_FEED_MSG_08', 'Wszystkie zadania dnia zostały wykonane i to w jeden dzień! Ma się to wprawę ;)');
define('LANG_PLATFORM_FEED_MSG_09', 'Moją wyspę prześladuje pech :( Proszę pomóż mi używając karty na pecha!');
define('LANG_PLATFORM_FEED_MSG_10', 'Otrzymuję super prezent! Chcesz też taki? To zagraj w Wyspę Marzeń!');
define('LANG_PLATFORM_FEED_MSG_11', 'Udało mi się zdobyć tajemniczy prezent w Wyspie Marzeń. Ty też możesz spróbować!');
define('LANG_PLATFORM_FEED_MSG_12', '{*user*}參加了快樂島主大團購活動，齊心協力撿便宜啦！ 你還在猶豫什麼呢？快點進入遊戲參活動吧！');
define('LANG_PLATFORM_FEED_MSG_13', 'Na mojej wyspie panuje ciężka nawałnica. Pomóż mi proszę!');
define('LANG_PLATFORM_FEED_MSG_14', 'Kolejne zadanie wykonane ;) Zagraj ze mną!');
define('LANG_PLATFORM_FEED_MSG_15' ,'Powiększam łódź na Wyspie Marzeń! Takiej łodzi jeszcze nikt nie widział!');
define('LANG_PLATFORM_FEED_MSG_16', 'Awansuję na {*level*} poziom! A moja wyspa marzeń jest coraz większa i piękniejsza :o)');
define('LANG_PLATFORM_FEED_MSG_17', 'Otwieram skrzynię i... A co w niej było, powiem Ci, jak mnie odwiedzisz na wyspie!');
define('LANG_PLATFORM_FEED_MSG_18', '幫幫他');
define('LANG_PLATFORM_FEED_MSG_19', 'Uwielbiam to!');
define('LANG_PLATFORM_FEED_MSG_20', '{*user*},在快樂島主的七夕活動中獲得了活動獎勵{*name*},他在這裡誠信祝願天下有情人終成眷屬');
define('LANG_PLATFORM_FEED_MSG_21', '七夕情人節“鵲橋之戀”活動開始啦，誰來送我鵲羽呀~');

define('LANG_PLATFORM_BASE_TXT_00', 'Wyspa Marzeń');
define('LANG_PLATFORM_BASE_TXT_01', ' Monety');
define('LANG_PLATFORM_BASE_TXT_02', ' Diament');
define('LANG_PLATFORM_BASE_TXT_03', 'Poziom');
define('LANG_PLATFORM_BASE_TXT_04', 'Doświadczenie');
define('LANG_PLATFORM_BASE_TXT_05', 'Dekoracje');
define('LANG_PLATFORM_BASE_TXT_06', 'Turyści');
define('LANG_PLATFORM_BASE_TXT_07', 'Przystań dla łodzi');
define('LANG_PLATFORM_BASE_TXT_08', 'Port');
define('LANG_PLATFORM_BASE_TXT_09', 'Obiekt');
define('LANG_PLATFORM_BASE_TXT_10', 'Diament');
define('LANG_PLATFORM_BASE_TXT_11', 'Dzienny bonus ');
define('LANG_PLATFORM_BASE_TXT_12', 'Gwiazda');
define('LANG_PLATFORM_BASE_TXT_13', 'Kup');
define('LANG_PLATFORM_BASE_TXT_14', 'Mamba');
define('LANG_PLATFORM_BASE_TXT_15', 'Plingowy prezent');
define('LANG_PLATFORM_BASE_TXT_16', ' Gwiazda');
define('LANG_PLATFORM_BASE_TXT_17', 'Otwórz');
define('LANG_PLATFORM_BASE_TXT_18', 'PD');
define('LANG_PLATFORM_BASE_TXT_19', 'Część');
define('LANG_PLATFORM_BASE_TXT_20', 'Odbierz łódź.');
define('LANG_PLATFORM_BASE_TXT_21', 'Zbierz górę Monet.');
define('LANG_PLATFORM_BASE_TXT_22', 'Zbuduj');
define('LANG_PLATFORM_BASE_TXT_23', 'Przyspiesz jedną łódź.');
define('LANG_PLATFORM_BASE_TXT_24', 'Wykonaj jedno zadanie.');
define('LANG_PLATFORM_BASE_TXT_25', 'Powiększ budynek.');
define('LANG_PLATFORM_BASE_TXT_26', 'Idź na wyspę Mamby.');
define('LANG_PLATFORM_BASE_TXT_27', 'Aktualizuj nagrodę.');
define('LANG_PLATFORM_BASE_TXT_28', 'Nagroda za tytuł');
define('LANG_PLATFORM_BASE_TXT_29', 'Nagroda za logowanie');
define('LANG_PLATFORM_BASE_TXT_30', 'Nagroda nowicjusza');
define('LANG_PLATFORM_BASE_TXT_31', 'Nagroda specjalna');
define('LANG_PLATFORM_BASE_TXT_32', 'Nagroda czasowa');
define('LANG_PLATFORM_BASE_TXT_33', ' przesyła.');
define('LANG_PLATFORM_BASE_TXT_34', 'Błąd danych.');
define('LANG_PLATFORM_BASE_TXT_35', 'Powiększ wyspę.');

define('LANG_PLATFORM_INDEX_TXT_00', 'Czas naprawy');
define('LANG_PLATFORM_INDEX_TXT_01', 'Rok');
define('LANG_PLATFORM_INDEX_TXT_02', 'Miesiąc');
define('LANG_PLATFORM_INDEX_TXT_03', 'Wyślij diamentowy prezent.');
define('LANG_PLATFORM_INDEX_TXT_04', 'Potrójny darmowy prezent jednego dnia');
define('LANG_PLATFORM_INDEX_TXT_05', 'Sugeruje wysłanie');
define('LANG_PLATFORM_INDEX_TXT_06', 'Prezenty za Diamenty');
define('LANG_PLATFORM_INDEX_TXT_07', 'znajomemu');
define('LANG_PLATFORM_INDEX_TXT_08', 'Potrzebujesz więcej Diamentów.');
define('LANG_PLATFORM_INDEX_TXT_09', 'Doładuj');
define('LANG_PLATFORM_INDEX_TXT_10', 'Problem przy uruchomieniu, proszę odśwież stronę.');
define('LANG_PLATFORM_INDEX_TXT_11', 'Brak wyspy');
define('LANG_PLATFORM_INDEX_TXT_12', 'Konto, {*uid*}, zostało zablokowane ze względu na nielegalne użycie oprogramowania. Skontaktuj się z serwisem.');
define('LANG_PLATFORM_INDEX_TXT_13', 'Konto, {*uid*}, zostało zablokowane ze względu na nadużycie. Skontaktuj się z serwisem.');
define('LANG_PLATFORM_INDEX_TXT_14', 'Konto, {*uid*}, zostało zablokowane ze względu na problemy z oprogramowaniem. Skontaktuj się z serwisem.');
define('LANG_PLATFORM_INDEX_TXT_15', 'Konto, {*uid*}, zostało tymczasowo zablokowane. Skontaktuj się z serwisem.');
define('LANG_PLATFORM_INDEX_TXT_16', 'Wyspa Marzeń');
define('LANG_PLATFORM_INDEX_TXT_17', 'Wyspa Fantazji');
define('LANG_PLATFORM_INDEX_TXT_18', 'Zagubiony Świat');
define('LANG_PLATFORM_INDEX_TXT_19', 'Karnawał');
define('LANG_PLATFORM_INDEX_TXT_20', 'Codzienna nagroda');
define('LANG_PLATFORM_INDEX_TXT_21', 'Codzienny bonus');
define('LANG_PLATFORM_INDEX_TXT_22', '{*nickname*} dostaje zaproszenie. Otrzymujesz 1000 Złota i 3 Gwiazdy! Odwiedź Sklep już teraz!');
define('LANG_PLATFORM_INDEX_TXT_23', 'Gratulacje! Otrzymujesz Kierowniczy Bonus!');

define('LANG_PLATFORM_EVENT_TXT_00', 'Musisz logować się codziennie przez 15 dni, aby odblokować.');
define('LANG_PLATFORM_EVENT_TXT_01', 'Nie możesz tego wymienić. Spróbuj z innym przedmiotem.');
define('LANG_PLATFORM_EVENT_TXT_02', 'Nie możesz jeszcze otworzyć tego przedmiotu. Spróbuj z innym przedmiotem.');
define('LANG_PLATFORM_EVENT_TXT_03', 'Twoja wyspa jest zbyt mała, aby powiększyć.');
define('LANG_PLATFORM_EVENT_TXT_04', 'Zły wybór, następnym razem spróbuj inne.');
define('LANG_PLATFORM_EVENT_TXT_05', 'Nie masz wystarczająco miejsca.');
define('LANG_PLATFORM_EVENT_TXT_06', 'Karta');
define('LANG_PLATFORM_EVENT_TXT_07', 'Elitarny pakiet II');
define('LANG_PLATFORM_EVENT_TXT_08', 'Elitarny pakiet I');
define('LANG_PLATFORM_EVENT_TXT_09', 'Pakiet nowicjusza II');
define('LANG_PLATFORM_EVENT_TXT_10', 'Pakiet nowicjusza I');
define('LANG_PLATFORM_EVENT_TXT_11', 'Miły pakiet');
define('LANG_PLATFORM_EVENT_TXT_12', 'Obronny pakiet');
define('LANG_PLATFORM_EVENT_TXT_13', 'Gratulacje! Wymiana powiodła się!');
define('LANG_PLATFORM_EVENT_TXT_14', 'Gratulacje! Otrzymujesz:');
define('LANG_PLATFORM_EVENT_TXT_15', 'Ta funkcja nie jest jeszcze odblokowana, proszę o cierpliwość.');
define('LANG_PLATFORM_EVENT_TXT_16', 'Już masz tę nagrodę. Sprawdź w magazynie.');
define('LANG_PLATFORM_EVENT_TXT_17', 'Otrzymujesz: ');
define('LANG_PLATFORM_EVENT_TXT_18', 'Sprawdź w magazynie!');
define('LANG_PLATFORM_EVENT_TXT_19', 'Gratulacje! To już 1 runda zadań! Prezenty są już w Twoim magazynie!.');
define('LANG_PLATFORM_EVENT_TXT_20', 'Gratulacje! To już 2 runda zadań! Prezenty są już w Twoim magazynie!.');
define('LANG_PLATFORM_EVENT_TXT_21', 'Gratulacje! To już 3 runda zadań! Prezenty są już w Twoim magazynie!.');
define('LANG_PLATFORM_EVENT_TXT_22', 'Gratulacje! To już 4 runda zadań! Prezenty są już w Twoim magazynie!.');
define('LANG_PLATFORM_EVENT_TXT_23', 'Kup');
define('LANG_PLATFORM_EVENT_TXT_24', 'Otrzymujesz specjalny pakiet!');
define('LANG_PLATFORM_EVENT_TXT_25', 'Za mało Gwiazdek!');
define('LANG_PLATFORM_EVENT_TXT_26', 'Gratulacje!');
define('LANG_PLATFORM_EVENT_TXT_27', 'Wymień');
define('LANG_PLATFORM_EVENT_TXT_28', 'Użyj');
define('LANG_PLATFORM_EVENT_TXT_29', 'Wyprzedaż zakończyła się. Spróbuj następnym razem!');
define('LANG_PLATFORM_EVENT_TXT_30', 'Jesteś w grupie kupujących. Poczekaj na dalsze informacje.');
define('LANG_PLATFORM_EVENT_TXT_31', 'Wyprzedaż zakończyła się. Spróbuj następnym razem!');
define('LANG_PLATFORM_EVENT_TXT_32', 'Już bierze udział w danej akcji.');
define('LANG_PLATFORM_EVENT_TXT_33', 'Kup');
define('LANG_PLATFORM_EVENT_TXT_34', 'Ostatni bonus!');
define('LANG_PLATFORM_EVENT_TXT_35', 'Po TOP 1000');
define('LANG_PLATFORM_EVENT_TXT_36', 'Otwórz skrzynię.');
define('LANG_PLATFORM_EVENT_TXT_37', '恭喜你在大轉盤中獲得');
define('LANG_PLATFORM_EVENT_TXT_38', 'Przeszukując skrzynie znajdujesz:');
define('LANG_PLATFORM_EVENT_TXT_39', 'Za mało części!');
define('LANG_PLATFORM_EVENT_TXT_40', 'Udana wymiana!');
define('LANG_PLATFORM_EVENT_TXT_41', 'Masz już wszystkie części!');
define('LANG_PLATFORM_EVENT_TXT_42', 'Masz za mało Diamentów!');
define('LANG_PLATFORM_EVENT_TXT_43', 'Limit zakupów na ten miesiąc został wyczerpany.');
define('LANG_PLATFORM_EVENT_TXT_44', 'Wymiana wykonana po zakupie części.');

define('LANG_PLATFORM_EXT_TXT_101', 'Ktoś używa na Twojej wyspie:{*name*}');
define('LANG_PLATFORM_EXT_TXT_102', 'Zablokowana przystań {*num*}, {*name*}');
define('LANG_PLATFORM_EXT_TXT_103', 'Powiększ o port {*num*}.');
define('LANG_PLATFORM_EXT_TXT_104', 'Powiększ: {*name*} do {*num*} Gwiazdek.');
