<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>プレゼント - ドリームワールド</title>
<link href="{%$staticUrl%}/apps/island/css.css?v=3" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>    
    <script type="text/javascript" language="javascript" src="http://mixi.jp/static/js/platform/json.js?1228977457"></script>
    <script type="text/javascript" language="javascript" src="http://mixi.jp/static/js/platform/rpc.js?1228977457"></script>
    
    <script type="text/javascript" language="javascript">
        gadgets.rpc.setRelayUrl('..', "{%$mixi_platform_api_url%}", false);
        
        function sendMessage(uid, title, body) {
            gadgets.rpc.call(null, 'remote_sendMessage', null, uid, title, body);
        }
        
        function adjustHeight(height) {
            gadgets.rpc.call(null, 'remote_adjustHeight', null, height);            
        }
        
        function postActivity(title, reciptents) {
            gadgets.rpc.call(null, 'remote_postActivity', null, title, reciptents);
        }

        function postActivityWithPic(title, picurl, mimeType, reciptents) {
            gadgets.rpc.call(null, 'remote_postActivityWithPic', null, title, picurl, mimeType, reciptents);
        }
        
        function voice(url) {
            gadgets.rpc.call(null, 'remote_voice', null, url, '');
        }
        
        function upAlbumPhoto(url) {
            gadgets.rpc.call(null, 'remote_upAlbumPhoto', null, url, '');
        }
        
        adjustHeight(880);
        
        {% if $sendMessage %}
        var uid = {% $userInfo.uid %};
        var message = '{% $message %}';
        var messageImg = '{% $messageImg %}';
        
        //postActivityWithPic(message, messageImg);
        voice(message + 'http://mixi.jp/run_appli.pl?id={%$smarty.const.APP_ID%}');
        //voice(message);
        //sendMessage(recipient, title, body);
        {% /if %}
    </script>
    
</head>
<body>
<div>
<a href="{%$baseUrl%}/pay/rewardplus"><img src="{%$staticUrl%}/apps/island/images/topbanner-1.jpg" /></a>&nbsp;<a href="{%$baseUrl%}/invite/top"><img src="{%$staticUrl%}/apps/island/images/topbanner-2.jpg" /></a>
</div>

<div class="main">
{%include file="menu.phtml"%}

<div class="content" style="height:700px">
<script type="text/javascript">
	var PAGE_NUM = 2;
	function hideAllPage()
	{
		var page = null;
		for(var i = 1; i <= PAGE_NUM; i++) {
			page = document.getElementById('page' + i);
			if (page) {
				page.style.display = 'none';
			}
		}
	}
	
	function goPage(i)
	{
		var page = document.getElementById('page' + i);
		if (page) {
			hideAllPage();
			page.style.display = 'block';
		}
	}

</script>
<!--<a href="javascript:void(0);" onclick="upAlbumPhoto('http://mixitest.hapyfish.com/static/apps/island/images/card.jpeg');">albumphoto</a>
--><form id="selectgifts" method="post" action="/gift/friends">
<div class="yaoqing02-1-1">
<div class="songchusuoxuan1"><input type="image" src="{%$staticUrl%}/apps/island/images/gift/songchusuanxuan.gif" /></div>
</div>
<div class="yaoqing02-2" style="padding-left: 45px; width: 705px; height: 550px;" id="page1">
<ul class="giftlist">
	{% foreach from=$giftList[0] item=data key=key %}
	<li><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}" width="80" height="80" />
	<div class="txt">{%$data.name%}</div>
	{% if $userInfo.level >= $data.level %}
	<div class="dian"><input name="gid" id="gid" type="radio" {%if $key== 0 %}checked="checked" {%/if%} value="{%$data.gid%}" /></div>
	{%else%} <span style="color: red;">レベル{%$data.level%}以上可</span> {%/if%}</li>
	{% /foreach %}
</ul>
<div align="right" style="width:650px"><a href="javascript:void(0);" onclick="goPage(1);"> 1 </a>&nbsp;<a href="javascript:void(0);" onclick="goPage(2);"> 2 </a>&nbsp;<a href="javascript:void(0);" onclick="goPage(2);">次</a></div>
</div>
<div class="yaoqing02-2" style="padding-left: 45px; width: 705px; height: 550px; display:none;" id="page2">
<ul class="giftlist">
	{% foreach from=$giftList[1] item=data key=key %}
	<li><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}" width="80" height="80" />
	<div class="txt">{%$data.name%}</div>
	{% if $userInfo.level >= $data.level %}
	<div class="dian"><input name="gid" id="gid" type="radio" {%if $key== 0 %}checked="checked" {%/if%} value="{%$data.gid%}" /></div>
	{%else%} <span style="color: red;">レベル{%$data.level%}以上可</span> {%/if%}</li>
	{% /foreach %}
</ul>
<div align="right" style="clear:both;width:650px"><a href="javascript:void(0);" onclick="goPage(1);">前</a>&nbsp;<a href="javascript:void(0);" onclick="goPage(1);"> 1 </a>&nbsp;<a href="javascript:void(0);" onclick="goPage(2);"> 2 </a></div>
</div>
<div class="yaoqing02-3">
<div class="songchusuoxuan2"><input type="image" src="{%$staticUrl%}/apps/island/images/gift/songchusuanxuan.gif"/></div>
</div>
<div class="mashangyaoqing"></div>
</form>
</div>

{%include file="footer.phtml"%}