<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>监测[{%$uid%}] | Pulau Bahagia</title>
<link href="{%$staticUrl%}/apps/island/main_2011012801.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}

object#swfcontent {
	display: inline;
}

.box {
	border: 1px solid #CCCCCC;
}
-->
</style>
</head>
<body>
<div class="main" style="height:700px;">
{%include file="menu.phtml"%}
	<div id="main_content">
		<div id="loadingdiv" style="position: absolute; left: 350px; top: 250px;"><img src="{%$staticUrl%}/apps/island/images/common/loading0.gif" /><br/>加载中......</div>
		<div id="flashdiv"></div>
		<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
		<script type="text/javascript" src="http://static.happyfishgame.com/natekr/js/jquery-1.4.3.min.js"></script>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;
			var FIRST_LOGIN = {%$newuser%};

			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
	        	var flashVars={"ver":"2","pNum":"46","uid":"{%$uid%}","loadingUi":"{%$staticUrl%}/swf/loadingUi2.swf?v=2011020901", "interfaceUrl":"{%$hostUrl%}/apiwatch/initswf?v=2011020901","snsType":"facebook"};
	        	var params = { base: "{%$staticUrl%}/", allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "true", bgcolor: "#ffffff", align: "middle", quality: "high"};
	        	var attrs = { id: "islandLoader", name: "islandLoader" };
	        	swfobject.embedSWF("{%$staticUrl%}/swf/islandLoader.swf?v=2011020901", "flashdiv",  "748", "600", "10.0", "{%$staticUrl%}/expressInstall.swf", flashVars, params, attrs);
	        } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">检测到您的浏览器没有开启或接收Cookie！请尝试开启后，重新进入。</div>'
	        	$('#flashdiv').html(html);
	        }

	        function hideLoading() {
	        	$('#loadingdiv').hide();
	        }
		</script>
	</div>
</div>
<script type="text/javascript">
	function goInvite()
	{
		location.href = '{%$hostUrl%}/invite/top';
	}

	function goPay()
	{
		return;
	}

	function showuser(uid, name, face)
	{
	}

	function reloadGame()
	{
		top.location.href = 'http://apps.facebook.com/{%$smarty.const.APP_NAME%}/';
	}

	function showuser(uid, name, face)
	{
		OWNER_ID = uid;
		var userinfo = document.getElementById('userinfo');
		if (userinfo) {
			if (OWNER_ID != VIEWER_ID) {
				userinfo.innerHTML = ' [当前好友门牌号：' + OWNER_ID + ']';
			} else {
				userinfo.innerHTML = '';
			}
		}
	}

	function nateToast(type, target, text) {
		var content = '';
		if (text == null || text == undefined) {
			text = '';
		}
		if (1 == type) {
			content = '이런!! 아일랜드에서{%$uname%}님이 기다리던 손님을 데려가 버렸어요!';
		}
		else if (2 == type) {
			content = '절친{%$uname%}님이 내 건축물의 돈을 가져가버렸어요! 두고보자!';
		}
		else if (3 == type) {
			content = '{%$uname%}님이 건축물을 고쳐줬어요. 음 그럴 친구는 아닌데 그죠? ^^';
		}
		else if (4 == type) {
			content = text;
		}
		else {
			return;
		}
		if (target == null || target == ''){
			return;
		}
		alert(content+target);
	}
</script>

 {%include file="footer.phtml"%}
