<div style="width:750px;">
<iframe width="750px" height="160px" frameborder="0" scrolling="no" src="{%$staticUrl%}/html/b/index.html?v=2011062201"></iframe>
<div id="footer" style="text-align:center;font-size:12px;">Số của đảo: {%$platformUid%} ({%$uid%}){% if $hfDev == 1 %}<span id="userinfo" style="color:red;"></span>{% /if %}</div>
</div>
<!-- 
<div>
<a href="#" onclick="testfeed();">testfeed</a><br/>
</div>
 -->
{%include file="cmscript.phtml"%}
</body>
</html>