
<div id="slider">
</div>
<div class="title">
	<div class="menu">
        <ul style="padding-left:170px;width:700px;">
        	<li style="width:76px;"><a href="http://happyislandvcc.snsplus.com/index/login"><img src="{%$staticUrl%}/apps/island/images/menu/v2/home.gif" title="Nhà" alt="Nhà" /></a></li>
        	<li style="width:88px;"><a href="#" onclick="showInvite();"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite.gif" title="Mời bạn" alt="Mời bạn" /></a></li>
        	<li style="width:76px;"><a href="{%$baseUrl%}/gift/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift.gif" title="Tặng quà" alt="Tặng quà" /></a></li>
        	<!--<li style="width:85px;"><a href="{%$baseUrl%}/pay/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/pay.gif" title="Nạp" alt="Nạp" /></a></li> -->
        	<li style="width:85px;"><a id="mnuPay" href="javascript:void(0);" onclick="topPay('{% if $connectSnsplus %}{%$connectSnsplus%}{% /if %}');"><img src="{%$staticUrl%}/apps/island/images/menu/v2/pay.gif" title="Nạp" alt="Nạp" /></a></li>
            <li style="width:68px;"><a href="http://forum.soha.vn/f69" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/forum.gif" title="Diễn đàn" alt="Diễn đàn" /></a></li>
        	<li style="width:68px;"><a href="http://forum.soha.vn/f87/" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/help.gif" title="Hướng dẫn" alt="Hướng dẫn" /></a></li>
        	<li style="width:104px;"><a href="{% $snsUrl %}" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/bo_4.gif" border="0" /></a>
        </ul>
	</div>
</div>
    <!--{% if $showNotice == true %}
	  <div class="guang">
    	  <div class="guang_b" style="clear:both;">
    	<!-- <div style="display:block;float:right; padding-top:3px;"><iframe scrolling="no" frameborder="0" allowtransparency="true" src="http://www.connect.renren.com/like?url=http%3A%2F%2Fpage.renren.com%2Frrisland" style="width: 140px;height: 22px;"></iframe></div> -->
    	 <!-- </div>
    	   <div style="clear:both;"></div>--> 
	  <!-- {% foreach from=$mainNotice item=data %}
    	 <!-- <div class="zleft guang_z">{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</div>
    	 {% /foreach %}
</div> 
{% /if %}--> 

<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
    });

    function reloadIsland()
    {
        var showUrl = "?signed_request="+signed_request;
        self.location.href = showUrl;
        return;
    }
</script>

<div id="payBox" style="width:750px; height:700px;position:absolute;left:5px;top:65px;display:none;background-color:white;margin-top:-16px;margin-left:-5px;">
    <div style="position: absolute; left:720px;top:8px;"><a id="mnuPayCls" href="javascript:void(0);"><img src="{%$staticUrl%}/apps/island/images/common/btnClose.png" /></a></div>
    <div id="divPayFrame" style=""></div>
</div>
<div id="feedbox" style="display:none;clear: both; position: absolute; left: 20px; top: 100px; border: medium none;"></div>
<div id="invitebox" style="display:none;clear: both; position: absolute; left: 20px; top: 100px; border: medium none;"></div>