<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ドリームワールド</title>
<link href="{%$staticUrl%}/apps/island/css.css?v=1" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<table width="536" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="278" background="{%$staticUrl%}/apps/island/images/chongzhishibai.gif"><table width="340" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="150">&nbsp;</td>
      </tr>
      <!-- <tr>
        <td height="40"><div align="center"><a href="{%$baseUrl%}/paypal/index" ><img src="{%$staticUrl%}/apps/island/images/chongshi.gif" width="129" height="31" /></a></div></td>
      </tr> -->
      <tr>
        <td height="40"><div align="center"><a href="#" onclick="window.opener=null;window.open('','_self');window.close();"><img src="{%$staticUrl%}/apps/island/images/guanchuang.gif" width="129" height="31" /></a></div></td>
      </tr>
    </table></td>
  </tr>
</table>

</body>
</html>