<link href="{%$staticUrl%}/apps/island/css_gift.css?v=1.17" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>

<div class="main" style="height:700px;">
<div class="bg">
<div class="sl01-bg01"></div>
<div class="sl01-bg02">
<div class="sl01-bg02-1 left"></div>
<div class="sl01-bg02-2 left"><a href="#" onclick="HFApp.giftTop({});"><img	src="{%$staticUrl%}/apps/island/images/gift2/sl01_03.gif" alt="PREZENTY" border="0" /></a></div>
<div class="sl01-bg02-3 left"><a href="#" onclick="HFApp.giftGet({});"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_04_new3.gif" alt="Otrzymane prezenty" border="0" /></a></div>
<div class="sl01-bg02-4 left"><a href="#" onclick="HFApp.giftPost({});"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_05_new3.gif" alt="Wysłane prezenty" border="0" /></a></div>
<div class="sl01-bg02-5 left"></div>
<div class="sl01-bg02-6 left"></div>
</div>
<div class="sl01-bg03">
<div class="sl01-li">
<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"" target="_parent"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
<div class="liwu-bss right">{%$userGold%} Diamentów</div>
<div class="liwu-bt right"><a href="#" onclick="HFApp.giftTop({tid:2});"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif" id="img2" alt="Prezenty za Diamenty" border="0" /></a></div>
<div class="liwu-bt right"><a href="#" onclick="HFApp.giftTop({tid:1});"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw.gif" id="img1" border="0" /></a></div>
</div>
</div>

<div class="sl01-bg04_1" id="type_4">
<div class="liwu-ul" style="padding-left:50px; padding-top:110px;text-align:center;font-size:14px; height:200px;color:#ff0000;">
  {%$msg%}
  <br/>
  <a href="{%$hostUrl%}/gift/top"><img src="{%$staticUrl%}/apps/island/images/gift2/fhyx.gif" border="0" /></a>
</div>
</div>

<div class="sl01-bg07">
<div class="sclw left" id="dosubmit3"><a href="javascript:void(0);" onclick="doSubmit(3)"></a></div>
<div class="sl02-zx left" id="page_3"></div>
</div>
<div class="sl01-bg08"></div>
</div>
<div class="zslw"></div>
</div>
