<link href="{%$staticUrl%}/apps/island/css_gift.css?v=1.17" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>

<div class="main">
  <div class="bg">
	<div class="sl01-bg01"></div>
	<div class="sl01-bg02">
		<div class="sl01-bg02-1 left"></div>
		<div class="sl01-bg02-2 left"><a href="#"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_03.gif" alt="Prezenty" border="0" /></a></div>
		<div class="sl01-bg02-3 left"><a href="#" onclick="HFApp.giftGet({});" ><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_04_new3.gif" alt="Otrzymane prezenty" border="0" /></a></div>
		<div class="sl01-bg02-4 left"><a href="#" onclick="HFApp.giftPost({});"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01_05_new3.gif" alt="Wysłane prezenty" border="0" /></a></div>
		<div class="sl01-bg02-5 left"></div>
		<div class="sl01-bg02-6 left"></div>
	</div>

	<div class="sl01-bg03">
		<span id="test_msg"></span>
		<div class="sl01-li" id="img1">
			<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
			<div class="liwu-bss right"> Diamentów：{%$userGold%} </div>
			<div class="liwu-bt right" style="padding-left:15px;"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="Prezenty za Diamenty" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img2" style="display:none">
			<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
			<div class="liwu-bss right"> Diamentów：{%$userGold%}</div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw-2.gif"  alt="Prezenty za Diamenty" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img3" style="display:none">
			<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
			<div class="liwu-bss right"> Diamentów：{%$userGold%} </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="Prezenty za Diamenty" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img4" style="display:none">
			<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
			<div class="liwu-bss right"> Diamentów：{%$userGold%} </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="Prezenty za Diamenty" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
		<div class="sl01-li" id="img5" style="display:none">
			<div class="liwu-cz right"><a href="#" onclick="HFApp.pay();"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-cz.gif" alt="Doładuj Diamenty." border="0" /></a></div>
			<div class="liwu-bss right"> Diamentów：{%$userGold%} </div>
			<div class="liwu-bt right" style="padding-left:15px"><a href="javascript:void(0);" onclick="showType(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-sclw.gif"  alt="Prezenty za Diamenty" border="0" /></a></div>
			<div class="liwu-bt right"><a href="javascript:void(0);" onclick="showType(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sl01-mflw-2.gif"  border="0" /></a></div>
		</div>
	</div>

	<form class="giftselect1" id="selectgifts1" method="post" action="{% if $connectSnsplus %}{%$hostUrl%}/gift/friends?{%$connectSnsplus%}{% else %}{%$hostUrl%}/gift/friends{% /if %}">
		<input type="hidden" name="tid" value="1" />
		<div class="sl01-bg04" id="type_1">
		{% foreach from=$giftFrees item=data_1 key=key_1%}
			<div class="liwu-ul" id="tab{%$key_1%}" style="padding-left:0px">
				<div style="padding-left:90px">
					{% foreach from=$data_1 item=data key=key %}
					<div class="mflw-li left" style="margin-bottom:20px">
						<div class="liwu-img right"><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}?v=20101208" width="100" height="100" /></div>
						<div class="liwu-txt right">{%$data.name%}<br /><br />
						{% if $userLevel >= $data.level %}
							<input type="hidden" name="MfcanSend" id="MfcanSend" value="-1" />
							<input type="radio" name="gid" onclick="MfSend();" value="{%$data.gid%}" />
						{%else%}
							<span style="color: red;">Zablokowane na {%$data.level%} poziomie.</span>
						{%/if%}
						</div>
					</div>
					{% /foreach %}
				</div>
			</div>
		{% /foreach %}
		</div>
	</form>

	<form class="giftselect3" id="selectgifts3" method="post" action="{% if $connectSnsplus %}{%$hostUrl%}/gift/friends?{%$connectSnsplus%}{% else %}{%$hostUrl%}/gift/friends{% /if %}">
		<input type="hidden" name="tid" value="3" />
		<div class="sl01-bg04" id="type_3" style="display:none;">
			<div class="liwu-ul"></div>
		</div>
	</form>

	<form class="giftselect2" id="selectgifts2" method="post" action="{% if $connectSnsplus %}{%$hostUrl%}/gift/friends?{%$connectSnsplus%}{% else %}{%$hostUrl%}/gift/friends{% /if %}">
		<input type="hidden" name="tid" value="2" />
		<input type="hidden" name="gift_value" id="gift_value" value="0" />
		<div class="sl01-bg04" id="type_2">
			{% foreach from=$giftCharges item=data_2 key=key_2 %}
			<div class="liwu-ul" id="tab_2{%$key_2%}" style="padding-left:0px"><div style="padding-left:90px">
				{% foreach from=$data_2 item=data key=key %}
					<div class="sflw-li left" style="margin-bottom:20px">
						<div class="liwu-img right"><img src="{%$staticUrl%}/apps/island/images/gift/items/{%$data.img%}" width="100" height="100" /></div>
						<div class="liwu-txt2 right">Cena：{%$data.price%}Diamentów<br />{%$data.name%}<br />
				  			{% if $userLevel >= $data.level %}
				  			<input type="hidden" name="canSend" id="canSend" value="-1" />
								<label>
									<input type="hidden" name="value_{%$data.gid%}" id="value_{%$data.gid%}" value="{%$data.price%}" />
									<input type="radio" name="gid" onclick="setGiftValue({%$data.price%})" value="{%$data.gid%}" />
								</label>
							{%else%}
								<span style="color: red;">Zablokowane na {%$data.level%} poziomie.</span>
							{%/if%}
						</div>
					</div>
				{% /foreach %}
				</div>
			</div>
			{% /foreach %}
		</div>
		<input type="hidden" name="histroy_value"  id="histroy_value" value="1" />
	</form>

	<div class="sl01-bg04_1" id="type_4">
		<div class="liwu-ul" style="padding-left:70px;padding-top:140px;text-align:center;font-size:14px;height:200px;color:#ff0000;">
		  <p>Za mało Diamentów! <a href="#" onclick="HFApp.pay();"><b>Doładuj</b></a> je teraz!<br/><br/></p>
		  <p><a href="javascript:void(0)"><img src="{%$staticUrl%}/apps/island/images/gift2/fhyx.gif" style='cursor:hand' onclick="goback()" border="0" /></a></p>
		</div>
	</div>
	<div class="sl01-bg04_1" id="type_5">
		<div class="liwu-ul" style="padding-left:70px;padding-top:140px;text-align:center;font-size:14px;height:200px;color:#ff0000;">
		  <p>Dar za darmo można wysłać tylko 3 razy w ciągu jednego dnia,<br/>Jeśli chcesz wysłać więcej prezentów, proszę wybrać <a href="#" onclick="HFApp.pay();"><b>diament prezent</b></a></p>
		  <p><a href="javascript:void(0)"><img src="{%$staticUrl%}/apps/island/images/gift2/fhyx.gif" style='cursor:hand' onclick="goback()" border="0" /></a></p>
		</div>
	</div>

	<div class="sl01-bg07">
		<div class="sclw left" id="dosubmit1"><a onclick="doSubmit(1)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" style="cursor:pointer ;" /></a></div>
		<div class="sclw left" id="dosubmit2"><a onclick="doSubmit(2)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" style="cursor:pointer ;" /></a></div>
		<div class="sclw left" id="dosubmit3" style="display: none;"><a onclick="doSubmit(3)"><img src="{%$staticUrl%}/apps/island/images/gift2/sclw.gif" border="0" /></a></div>
		<div class="sclw left" id="dosubmit4"></div>
		<div class="sclw left" id="dosubmit5"></div>

		<div class="sl02-zx left" id="page_1">{% foreach from=$giftFrees item=data_1 key=key_1 %}<a href="javascript:void(0);" id="pag1_{%$key_1%}" class="cur_cls" onclick="showTab({%$key_1%})">[{%$key_1+1%}]</a>{% /foreach %}</div>
		<div class="sl02-zx left" id="page_2">{% foreach from=$giftCharges item=data_1 key=key_1 %}<a href="javascript:void(0);" id="pag2_{%$key_1%}" class="cur_cls" onclick="showTab_2({%$key_1%})">[{%$key_1+1%}]</a>{% /foreach %}</div>
		<div class="sl02-zx left" id="page_3"></div>
		<div class="sl02-zx left" id="page_4"></div>
		<div class="sl02-zx left" id="page_5"></div>
	</div>
	<div class="sl01-bg08"></div>
  </div>
</div>

<script type="text/javascript">
	var user_gold = "{%$userGold%}";
	var site_url = '{%$staticUrl%}';
	var gift_value = 0;
	var count = '{%$count%}';

	function doSubmit(i) {
		var sub_obj = null;
		switch(i) {
			case 1:
				//sub_obj = $('#selectgifts1');
				var MfcanSend = $('#MfcanSend').val();
				if(MfcanSend != 1) {
					return false;
				}
			break;
			case 2:
				//sub_obj = $('#selectgifts2');
				$('#histroy_value').val(2);
				var gift_value = $('#gift_value').val();

				var canSend = $('#canSend').val();
				if( canSend != 1 ) {
					return false;
				}
	     	break;
			case 3:
				//sub_obj = $('#selectgifts3');
				gift_value = $('#gift_value').val();
				$('#histroy_value').val(3);
			break;
		}

		if(i != 1) {
			if(parseInt(gift_value) == '0') {
	        	return false;
			}

	     	else if(parseInt(gift_value) > parseInt(user_gold)) {
	       		showType(4);
	       		return false;
	     	}
		} else {
			if(count <= 0) {
				showType(5);
				return false;
			}
		}

		//sub_obj.submit();
		var gid = $("#selectgifts"+i+" input:radio[name='gid'][checked]").val();
		/*$.each($('#selectgifts'+i+' :radio'), function(i, n){
			$.each(n, function(u,v){alert( "Item #" + i + ": " + u + '|' + v );});

	    });*/
		HFApp.giftFriend({'tid': i, 'gid': gid});
		return false;
	}

	function goback() {
		var histroyid = document.getElementById('histroy_value').value;
		showType(parseInt(histroyid));
	}

	function setGiftValue(value) {
		$('#gift_value').val(value);
		$('#canSend').val(1);
	}

	function MfSend() {
		$('#MfcanSend').val(1);
	}

	function showTab(j) {
		var k = {% $freeCount %};
		var i = 0;

		for(i=0; i<k; i++) {
			if(i == j) {
				document.getElementById('tab'+i).style.display = '';
				document.getElementById('pag1_'+i).className = 'cur_cls2';
			} else {
				document.getElementById('tab'+i).style.display = 'none';
				document.getElementById('pag1_'+i).className = 'cur_cls';
			}
		}
	}

	function showTab_2(j) {
		var k = {%$chargeCount%};
		var i = 0;

		for(i=0; i<k; i++) {
			if(i == j) {
				document.getElementById('tab_2'+i).style.display = '';
			} else {
				document.getElementById('tab_2'+i).style.display = 'none';
			}
		}
	}

	function showType(j) {
		var k = 5;
		for(i=1; i<=k; i++) {
			if(i == j) {
				var obj = document.getElementById('type_'+i);
			   		obj.style.display = '';
				var page_obj = document.getElementById('page_'+i);
					page_obj.style.display = '';
				var sub_obj = document.getElementById('dosubmit'+i);
					sub_obj.style.display = '';
				var img_obj = document.getElementById('img'+i);
	           		img_obj.style.display = '';
			} else {
				var obj = document.getElementById('type_'+i);
			   		obj.style.display = 'none';
				var page_obj = document.getElementById('page_'+i);
					page_obj.style.display = 'none';
				var sub_obj = document.getElementById('dosubmit'+i);
	           		sub_obj.style.display = 'none';
				var img_obj = document.getElementById('img'+i);
	           		img_obj.style.display = 'none';
			}
		}
	}
	showTab(0);
	showTab_2(0);
	showType({%$cid%});
</script>