<link href="{%$staticUrl%}/apps/island/css_2011012801.css?v=1.01" rel="stylesheet" type="text/css" />
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/apps/island/a/gb_app.css">
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
#queryDiv {
display:none;
left:240px;
top:350px;
position:absolute;
}
-->
</style>
<div class="main">
	{%include file="menu.phtml"%}
	<div id="main_content" class="content" style="padding-top:2px;">
		<div class="gift_friend_area_1" style="background-image: url('{%$staticUrl%}/apps/island/images/invite/invitehead.gif');"></div>
		<div class="gift_friend_area_2" style="height: 510px;">
    		<div class="gift_friend_left">
        		<div class="gift_item"><img src="{%$user.face%}" width="76" height="76" />
        		<div class="txt">{%$user.name|escape%}</div>
        		</div>
        		{%*<div align="center" style="margin-top: 5px; margin-left: -15px;"><label id="scount" style="width: 20px; color: red;">{%$giftSendNum%}</label>회 남았습니다</div>*%}
    		</div>
    		<div id="friend_content" class="gift_friend_right" style="height:450px;"></div>
    		<div id="div_send_button" align="center" style="clear:both;padding-top:5px;">
    		{%if $friendNum > 0 %}
    			<input id="btnSend" type="image" height="30px" src="{%$staticUrl%}/apps/island/images/invite/doinvit.gif"  onclick="send();" />
    			<input id="btnSendDisabled" style="display:none;" type="image" src="{%$staticUrl%}/apps/island/images/gift/send_disabled.gif" onclick="return false;" />
    		{%/if%}
    		</div>
		</div>
		<div class="gift_friend_area_3"></div>
	</div>

<div style="width: 417px; display: none;" class="layer_global" id="queryDiv">
	<div class="layer_global_main">
		<div class="layer_global_title"><h3>선물 발송 결과</h3><button title="close" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
		<div class="layer_global_cont">
			<div style="margin: 20px;" class="wrap"><span id="gift_send_result"></span></div>
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
	var FRIEND_LIST = {%$friendList%};
	var FRIEND_NUM = {%$friendNum%};
	var FRIEND_PER_PAGE = {%$pageSize%};
	var FRIEND_PAGE_NUM = {%$pageNum%};
	var STATIC_URL = '{%$staticUrl%}';
	var sendCounter = 0;

	function escapeHTML(html)
	{
		var escaped = html;
		var findReplace = [[/&/g, "&amp;"], [/</g, "&lt;"], [/>/g, "&gt;"], [/"/g, "&quot;"]]
		for(var item in findReplace) {
    		escaped = escaped.replace(item[0], item[1]);
    	}
    	return escaped;
	}

	function check(id)
	{
		var boxid = 'boxid_' + id;
		var obj = document.getElementById(boxid);
		if(obj){
			var curCount = sendCounter;
			if (obj.checked) {
				sendCounter--;
				if (FRIEND_LIST[id]) {
					FRIEND_LIST[id].selected = 1;
				}
			} else {
				sendCounter++;
				if (FRIEND_LIST[id]) {
					FRIEND_LIST[id].selected = 0;
				}
			}
			//$('#scount').html(sendCounter);
			//if (curCount <= 0 || sendCounter <= 0) {
			//	showPage(curPage);
			//}
        }
	}

	function send()
	{

		var fids = [];
		for(var i = 0 ; i < FRIEND_NUM; i++) {
			if (FRIEND_LIST[i].selected) {
				fids.push(FRIEND_LIST[i].uid);
				//FRIEND_LIST[i].selected = 0;
			}
		}
		if (fids.length == 0) {
			return;
		}

		fids = fids.join(',');
		//$('#btnSend').hide();
		//$('#btnSendDisabled').show();
		var pardata = {fids:fids};
	    if (_Config.hf_skey != "") {
	    	pardata['hf_skey'] = _Config.hf_skey;
	    }

		HFApp.inviteApi2(fids);
		return;

	    var param = {};
	    param[gadgets.io.RequestParameters.METHOD] = gadgets.io.MethodType.POST;
	    param[gadgets.io.RequestParameters.CONTENT_TYPE] = gadgets.io.ContentType.JSON;
	    param[gadgets.io.RequestParameters.POST_DATA] = gadgets.io.encodeValues(pardata);
	    param[gadgets.io.RequestParameters.AUTHORIZATION] = gadgets.io.AuthorizationType.NONE;
	    gadgets.io.makeRequest(_Config.giftsendUrl, function(response) {
		    var data = response.data;
	    	var html = '';
			if (data.errno != 0) {
				html = '데이터 에러[' + data.errno + ']';
			} else {
				html = '선택한 친구수:' + data.count + ',발송 성공 수:' + data.num;
				GIFT_SEND_NUM -= data.num;
				sendCounter = GIFT_SEND_NUM;
				if (sendCounter > 0) {
					$('#btnSend').show();
					$('#btnSendDisabled').hide();
					$('#scount').html(sendCounter);
				}
				showPage(1);
			}
			$('#gift_send_result').html(html);
			$('#queryDiv').show();
	    }, param);

		/*$.post('/gift/send', dt, function(data) {
			var html = '';
			if (data.errno != 0) {
				html = 'Salah hantar data[' + data.errno + ']';
			} else {
				html = 'Jumlah kawan pilih:' + data.count + ',Jumlah berjaya hantar:' + data.num;
				GIFT_SEND_NUM -= data.num;
				sendCounter = GIFT_SEND_NUM;
				if (sendCounter > 0) {
					$('#btnSend').show();
					$('#btnSendDisabled').hide();
					$('#scount').html(sendCounter);
				}
				showPage(1);
			}
			$('#gift_send_result').html(html);
			$('#queryDiv').show();
		}, "json");*/
	}

	function closeQuery()
	{
		$('#queryDiv').hide();
	}

	function showPage(i)
	{
		if (i <= 0 || (FRIEND_NUM > 0 && i > FRIEND_PAGE_NUM)) {
			return;
		}
		var html = ''
		if (FRIEND_NUM == 0) {
			html = '<div style="padding-top:100px;text-align:center">아직 아일랜드에 친구들이 없네요, 빨리 <a href="javascript:void(0);" onclick="HFApp.invite();">친구</a>들을 초청하세요.</div>';
		} else {
			curPage = i;
			var k = 0;
			var start = (i-1) * FRIEND_PER_PAGE;
			var end = start + FRIEND_PER_PAGE;
			if (end > FRIEND_NUM) {
				end = FRIEND_NUM;
			}
			html = '<ul class="friendlist" style="height:420px;">';
			for(var j = start; j < end; j++) {
				html += '<li><div class="name_area"><div class="checkbox"><p><input name="ids[]" type="checkbox" value="'
					  + FRIEND_LIST[j].uid + '" id="boxid_' + j + '"';
				/*if (FRIEND_LIST[j].selected) {
					html+= ' checked="true"';
				} else {
					if (sendCounter <= 0) {
						html += ' disabled="true"';
					}
				}*/
				html += ' onclick="check(' + j + ');" /></p></div><div class="face"><img src="'
					 + FRIEND_LIST[j].face + '" /></div><div class="nickname">'
					 + escapeHTML(FRIEND_LIST[j].name) + '</div></div></li>';

			}
			html += '</div></ul><div align="center" style="width:546px">';
			if (i > 1) {
				html += '<a href="javascript:void(0);" onclick="showPage(' + (i-1) + ');"> ' + '이전 페이지 </a>&nbsp;';
			}
			for(j = 1; j <= FRIEND_PAGE_NUM; j++) {
				if (j != i) {
					html += '<a href="javascript:void(0);" onclick="showPage(' + j + ');"> ' + j + ' </a>&nbsp;';
				} else {
					html += ' ' + j + ' &nbsp;';
				}
			}
			if ( i < FRIEND_PAGE_NUM) {
				html += '<a href="javascript:void(0);" onclick="showPage(' + (i+1) + ');"> ' + '이후 페이지 </a>&nbsp;';
			}
			html += '</div>';
		}

		$('#friend_content').html(html);
	}
	var curPage = 1;
	showPage(1);
</script>