<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ドリームワールド</title>
<link href="{%$staticUrl%}/apps/island/css.css?v=1" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<form id="frmPayOrder" method="GET" action="{%$baseUrl%}/paypal/payment">
<input type="hidden" name="uid" value="{%$uid%}">
<table style="width:748px;" "width="748px" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="450" background="{%$staticUrl%}/apps/island/images/chongzhi-bg.gif">
    <table width="650" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="40">&nbsp;</td>
      </tr>
    </table>
      <table width="652" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td width="468" height="36">ご購入いただいたダイヤはドリーム☆アイランドのみでご利用いただけます。<br />
          クレジットカード決済システムはPaypalを利用しています。</td>
        <td width="184"><img src="{%$staticUrl%}/apps/island/images/card.jpg" width="170" height="31" /></td>
      </tr>
    </table>
    
    <table stu width="670" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td width="140" height="140" valign="bottom"><div align="center"><img src="{%$staticUrl%}/apps/island/images/chongzhi01.jpg" alt="値段:500円" width="115" height="114" /></div></td>
          <td width="140" valign="bottom"><div align="center"><img src="{%$staticUrl%}/apps/island/images/chongzhi02.jpg" alt="値段:1000円" width="115" height="114" /></div></td>
          <td width="140" valign="bottom"><div align="center"><img src="{%$staticUrl%}/apps/island/images/chongzhi03.jpg" alt="値段:2000円" width="115" height="114" /></div></td>
          <td width="160" valign="bottom"><div align="center"><img src="{%$staticUrl%}/apps/island/images/chongzhi04.jpg" alt="値段:3000円" width="115" height="114" /></div></td>
          <td width="160" valign="bottom"><div align="right"><img src="{%$staticUrl%}/apps/island/images/chongzhi05.jpg" alt="値段:5000円" width="115" height="114" /></div></td>
        </tr>
        <tr>
          <td height="30"><div align="center">値段:500円</div></td>
          <td><div align="center">値段:1000円</div></td>
          <td><div align="center">値段:2000円</div></td>
          <td><div align="center">値段:3000円</div></td>
          <td><div align="center">値段:5000円</div></td>
        </tr>
        <tr>
          <td height="30"><label>
            <div align="center">
              <input type="radio" name="payRadio" value="500" />
            </div>
          </label></td>
          <td><div align="center">
            <input type="radio" name="payRadio" value="1000" />
          </div></td>
          <td><div align="center">
            <input type="radio" name="payRadio" value="2000" checked />
          </div></td>
          <td><div align="center">
            <input type="radio" name="payRadio" value="3000" />
          </div></td>
          <td><div align="center">
            <input type="radio" name="payRadio" value="5000" />
          </div></td>
        </tr>
      </table>
      <table width="700" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td><div align="center"><input type="image" value="submit" src="{%$staticUrl%}/apps/island/images/buy.jpg" /></div></td>
        </tr>
      </table>
      <br>
      <div align="right" style="padding-right:30px"><a target="_blank" href="http://play-w.com/di_kiyaku.html">利用規約</a></div>
      </td>
  </tr>
</table>

</form>
</body>
</html>