<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ドリームワールド</title>
<link href="{%$staticUrl%}/apps/island/css.css?v=1" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/cross_domain.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>

<table width="537" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="277" background="{%$staticUrl%}/apps/island/images/chongzhichenggong.gif"><table width="341" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td height="120" colspan="2">&nbsp;</td>
      </tr>
      <tr>
        <td width="142">&nbsp;</td>
        <td width="199" height="60">チャージ金額{%$pay.amont%}円<br />
ダイヤ{%$pay.gold%}個取得</td>
      </tr>
      <tr>
        <td height="60" colspan="2"><div align="center"><a href="http://mixi.jp/run_appli.pl?id={%$smarty.const.APP_ID%}"><img src="{%$staticUrl%}/apps/island/images/fanhuiyouxi.gif" alt="アプリに戻る" width="129" height="31" /></a></div></td>
      </tr>
      
    </table></td>
  </tr>
</table>

</body>
</html>